config/routes.rb
# Diese Datei kümmert sich um das Weiterleiten der Browser Anfragen
Rails.application.routes.draw do
  
  # Zunächst definieren wir mit 'root', was unsere Startseite ist
  root 'static_pages#home'
  
  # SSE Test
  get 'user_stream' => 'users#index_stream'
  get 'user_watch' => 'users#watch'
  # SSE Ende Test

  # Definieren wir erstmal unsere nicht so interessanten Seiten
  # Es gibt einen Controller 'StaticPages', welcher uns einfach nur "statische"
  # Seiten Anzeigen lassen soll. 
  
  # Es gilt: get 'DieUrlDerSeite' => 'ControlerNamen # Methode'
  # Bsp. mit '...de/help' wird die Methode 'help' des Controller 'StaticPages'
  # aufgerufen
  get    'help'      => 'static_pages#help' 
  get    'home'      => 'static_pages#home' # Die Startseite
  get    'about'     => 'static_pages#about' 
  get    'contact'   => 'static_pages#contact'
  get    'admin_menu'=> 'static_pages#admin_menu' # Die Admin Menu Seite

  # Definieren wir als nächstes, welche Modelle wir sehen wollen
  # Die Standartmethoden werden hierdurch erlaubt
  resources :firecars
  resources :users
  resources :professions
  resources :departments
  resources :addresses
  resources :operations do
    member do
      # Weiterhin wird die Methode 'map' erlaubt/definiert
      # Diese leitet die Anfrage an den 'OperationController'
      # weiter an die gleichnamige Methode
      get 'map' 
    end
  end
  
  # Routen für Passwörter etc.
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
  get    'users/delete_picture' => 'users#delete_picture'
  get    'signup'    => 'users#new'
  
  

  
  
  post   'static_pages/call_controller_post_method' => 'static_pages#call_controller_post_method'
  get   'static_pages/call_controller_method' => 'static_pages#call_controller_method'
  
  # Routen zum erstellen einer Session
  get 'sessions/new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def call_controller_post_method()
        controller_name = params[:controller_name]
        method_name = params[:method_name]
        custom = params[:custom]
      
        result = StaticPagesController.call_controller_method(controller_name,method_name,custom)
        
        redirect_to controller: 'static_pages', action: 'admin_menu', sql_result: result
        
        #redirect_to request.referrer || root_url
  end

  def call_controller_method()
        controller_name = params[:controller_name]
        method_name = params[:method_name]
        custom = params[:custom]
      
        return StaticPagesController.call_controller_method(controller_name,method_name,custom)
        
        #redirect_to request.referrer || root_url
  end
  
  def self.call_controller_method(controller_name,method_name,custom)
        controller = (controller_name + 'Controller').constantize
        
        meth = controller.method(method_name)
        
        return meth.call(custom)
  end
  
  def self.sql(query)
    sql = query.to_s
    records_array = ActiveRecord::Base.connection.execute(sql)
    result = records_array
    
    return result
  end



  def home
    if logged_in?
      
    else
      redirect_to '/login'
    end
  end

  def help
  end
  
  def admin_menu
  end

  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  HIer stehen noch weitere Informationen
</p>

app/views/static_pages/admin_menu.erb
<div class="row">
    <div class="col-md-4">

        <% map_icon = render "helper/icon" , locals: {:icon => "fa-desktop" } %>
        <%= render "helper/button_link" , locals: {:link => users_url, 
                                            :left => map_icon,
                                            :center => "Karte",
                                            :text => "Karten Ansicht" } %>          
    </div>
    <div class="col-md-4">
  
        <% if current_user.admin? %>

            <% list_icon = render "helper/icon" , locals: {:icon => "fa-list" } %>
            <%= render "helper/button_link" , locals: {:link => users_url, 
                                            :left => list_icon,
                                            :center => "User",
                                            :text => "Übersicht aller User" } %>
    
        <% end %>  
  
  
    </div>
    <div class="col-md-4">
      
                    
        <% mobile_icon = render "helper/icon" , locals: {:icon => "fa-mobile" } %>
        <%= render "helper/button_link" , locals: {:link => root_url, 
                                            :left => mobile_icon,
                                            :center => "Root URL",
                                            :text => "Zurück zum Hauptbildschirm" } %>   
    
    
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        
        <% javascript_body = render "shared/sql_query" %>   
        <%= render "helper/panel" , locals: {:title => "Javascript SQL Query:", :body => javascript_body } %>
    </div>
</div>




<div class="row">
    <div class="col-md-12">
        
        <% if params[:sql_result] != nil %>
            <% sql_result = render "helper/panel" , locals: {:title => "SQL Result:", :body => params[:sql_result] } %>
        <% else %>
            <% sql_result = "" %>
        <% end %>
        
        <%sql_button = form_tag('/static_pages/call_controller_post_method') do %>
            <%= hidden_field_tag 'controller_name', 'StaticPages' %>
            <%= hidden_field_tag 'method_name', 'sql' %>
            <%= text_area_tag :custom, params[:custom], :required => 'required', class: 'form-control', :size =>"25x5" %>
            <div class="btn btn-link">
                <%= submit_tag "Generate Query" %>
            </div>
        <% end %>
        
           
        
        <%= render "helper/panel" , locals: {:title => "Old SQL Query:", :body => sql_button+sql_result } %>
    </div>
</div>
  

<!--  -->

app/views/static_pages/beamer.erb
<%= render 'shared/beamerinformation' %>

<div class="row">
  <div id="beamer_title"></div>
  <div id="beamer_header"></div>
  <div id="beamer_result"></div>
  <div id="beamer_winner"></div>
</div>
    
    

<script type="text/javascript">
  $(document).ready(function () {
    $("#header_container").toggle(false);
    $("body").attr('style','padding-bottom:0px !important; padding-top:0px !important; overflow: hidden !important;');
  });
</script>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Kontakt</h1>
<p>
  Das ist die Kontakt Seite
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Das ist eine Hilfe Seite
</p>

app/views/static_pages/home.html.erb
<% slideTimeInSeconds = 10 %>

<% image_folger = "static_pages_wallpaper/" %>
<% images = ["1.jpg","2.jpg","3.jpg"] %>
<% image1 = "gesamtbild.png" %>

<%= render 'shared/reloadinformation' %>
<% if logged_in? %>
  
  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% first = true %>
    <% images.each do |image,i| %>
        <li data-target="#myCarousel" data-slide-to="<%= i %>" <% if first %>class="active"<% end %>></li>
        <% first = false %>
    <% end %>
  </ol>
    
    <div class="carousel-inner">
    <% first = true %>
    <% images.each do |image,i| %>
        <% if first %>
            <div class="item active">
        <% else %>
            <div class="item">
        <% end %>
                <img src="<%= image_folger %><%= image %>" alt="Chania">
                <div class="carousel-caption">
                    <h3>Los Angeles</h3>
                    <p>LA is always so much fun!</p>
                </div>
            </div>
        
        
        <% first = false %>
    <% end %>
  
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    
    <% left_icon = render "helper/icon" , locals: {:icon => "fa-chevron-left" } %>
    <span class="vertical-center" ><%= left_icon %></span>
    
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
      
    <% right_icon = render "helper/icon" , locals: {:icon => "fa-chevron-right" } %>
    <span class="vertical-center" ><%= right_icon %></span>
    
    <span class="sr-only">Next</span>
  </a>
</div>
  
  
<% end %>




<script type="text/javascript">
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none"; 
    }
    slideIndex++;
    if (slideIndex> slides.length) {slideIndex = 1} 
    slides[slideIndex-1].style.display = "block"; 
    setTimeout(showSlides, <%= slideTimeInSeconds %>*1000); // Change image every 2 seconds
}
</script>

app/views/static_pages/menu.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "qUos", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            
            <% if !logged_in? %>
            <li><%= link_to "Beamer", beamer_url %></li>
            <li><%= link_to "Hilfe", help_path %></li>
            <li><%= link_to "Anmelden", login_path %></li>
            <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Fragen", questions_url %></li>
            <li><%= link_to "Antworten", answers_url %></li>
            <li><%= link_to "Benutzer", users_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Abmelden", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>