config/routes.rb
# Diese Datei kümmert sich um das Weiterleiten der Browser Anfragen
Rails.application.routes.draw do
  
  # Zunächst definieren wir mit 'root', was unsere Startseite ist
  root 'static_pages#home'
  
  # SSE Test
  get 'user_stream' => 'users#index_stream'
  get 'user_watch' => 'users#watch'
  # SSE Ende Test

  # Definieren wir erstmal unsere nicht so interessanten Seiten
  # Es gibt einen Controller 'StaticPages', welcher uns einfach nur "statische"
  # Seiten Anzeigen lassen soll. 
  
  # Es gilt: get 'DieUrlDerSeite' => 'ControlerNamen # Methode'
  # Bsp. mit '...de/help' wird die Methode 'help' des Controller 'StaticPages'
  # aufgerufen
  get    'help'      => 'static_pages#help' 
  get    'home'      => 'static_pages#home' # Die Startseite
  get    'about'     => 'static_pages#about' 
  get    'contact'   => 'static_pages#contact'
  get    'admin_menu'=> 'static_pages#admin_menu' # Die Admin Menu Seite

  # Definieren wir als nächstes, welche Modelle wir sehen wollen
  # Die Standartmethoden werden hierdurch erlaubt
  resources :firecars
  resources :users
  resources :professions
  resources :departments
  resources :addresses
  resources :operations do
    member do
      # Weiterhin wird die Methode 'map' erlaubt/definiert
      # Diese leitet die Anfrage an den 'OperationController'
      # weiter an die gleichnamige Methode
      get 'map' 
    end
  end
  
  # Routen für Passwörter etc.
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
  get    'users/delete_picture' => 'users#delete_picture'
  get    'signup'    => 'users#new'
  
  

  
  
  post   'static_pages/call_controller_post_method' => 'static_pages#call_controller_post_method'
  get   'static_pages/call_controller_method' => 'static_pages#call_controller_method'
  
  # Routen zum erstellen einer Session
  get 'sessions/new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  #has_many :professions, dependent: :destroy
  has_and_belongs_to_many :professions #Ein User kann mehere Profession besitzten
  belongs_to :department #Ein User gehört einem Department an
  
  attr_accessor :remember_token
  validates :email,  presence: true, length: { maximum: 50 },
                    uniqueness: { case_sensitive: false }
                    
  validates :firstname,  presence: true, length: { maximum: 50 }
  validates :lastname,  presence: true, length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true
  
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  
  scope :last_updated, -> {
    order('updated_at DESC, created_at DESC').limit(1)
  }

 

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    Answer.where("user_id = ?", id)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def create_avatar_for_user
    image_user = self
    
    filename = image_user.email.gsub('@','_')+'.png'
    
    img = Avatarly.generate_avatar(image_user.firstname+" "+image_user.lastname, opts={})
    path_to_image = 'public/uploads/user/'+image_user.id.to_s+'/'+filename
    dirname = File.dirname(path_to_image)
    unless File.directory?(dirname)
      FileUtils.mkdir_p(dirname)
    end
    File.open(path_to_image, 'wb') do |f|
      f.write img
      image_user.picture = f
      image_user.save!
    end
    
  end
  
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
  
end

app/controllers/users_controller.rb
require 'reloader/sse'  # Damit SSE Emöglich sind

class UsersController < ApplicationController
  include ActionController::Live  # Damit SSE Emöglich sind
  
  before_action :logged_in_user, only: [:show, :delete_picture, :index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:show, :destroy, :delete_picture, :index]

  def index
    @users = User.paginate(page: params[:page], :per_page => 10)
  end
  
  
  # Damit SSE Emöglich sind
  def index_stream
    # SSE expects the `text/event-stream` content type
    response.headers['Content-Type'] = 'text/event-stream'

    sse = Reloader::SSE.new(response.stream)

    last_updated = User.last_updated.first
    
    if recently_changed? last_updated
      begin
        sse.write(last_updated, event: 'results')
      rescue IOError
        # When the client disconnects, we'll get an IOError on write
      ensure
        sse.close
      end
    end
    
    render :nothing => true
  end
  
  # Damit SSE Emöglich sind
  def recently_changed? last_user
    last_user.created_at > 5.seconds.ago or
      last_user.updated_at > 5.seconds.ago
  end


  def show
    @user = User.find(params[:id])
    @professions = @user.professions
    @professions = @professions.paginate(:page => params[:professions_page], :per_page => 3)
    #@answers = @user.answers.paginate(page: params[:page])
    #@questions = @user.questions.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Benutzer gelöscht"
    redirect_to users_url
  end

  def create
    name  = Faker::Name.name
    password = "password"
     @user = User.create!(name:  name,
               password:              password,
               password_confirmation: password)
               
    @user.name = "Benutzer "+@user.id.to_s
    @user.display_name = @user.name
    @user.last_activ = DateTime.now
    
    if request.user_agent != nil
      @user.device_type = request.user_agent
    else
      @user.device_type = "Console"
    end
    
    if @user.save
      log_in @user
      # flash[:success] = "Willkommen bei qUos"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def delete_picture
     @user = User.find(params[:id])
     @user.remove_picture!
     @user.save
     redirect_to request.referrer || root_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profil aktualisiert"
    end
    
    ajax = params[:ajax]
    if ajax
      render :nothing => true
    else
      redirect_to request.referrer || root_url    
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:last_activ, :firstname, :email, :password,
                                   :password_confirmation, :display_name, :picture)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Bitte anmelden."
        redirect_to login_url
      end
    end
    
     # Confirms the correct user or admin.
    def correct_user
      @user = User.find(params[:id])
      
      
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.1.erb
<!-- Das ist die Miniaturansicht eines Users -->


<%= csrf_meta_tag %> <!-- Damit bei einem AJAX Call der Auth. Token mitgesendet wird -->
<%= form_for(user, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
<% if !defined?(locals) %>
    <% player_number = user.id %>
<% else %>
    <% player_number = locals[:player_number] %>
<% end %>

<div class="col-xs-6">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h5 class="panel-title">User <%= player_number %></h5>
        </div>
        <div class="panel-body">
            <%= text_field_tag user.id, user.firstname, class: "answinput" , :id => user.id %>
            <%= text_field_tag user.id, user.lastname, class: "answinput" , :id => user.id %>
            <% if user.picture? %>
            

            <% open_label = '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe %>
            <% delte_button = link_to :controller => "users", :action => "delete_picture", :id => user.id  do %><div class="btn btn_question btn-danger icon">Löschen</div><% end %>
            <% content = "Sicher das Bild löschen?" %>

            <% dialog_button = render "helper/dialog_box" , locals: {:dialog_id => "dialog_box_"+user.id.to_s,
                                            :title => "Löschen", 
                                            :open_label => open_label,
                                            :dialog_content => content,
                                            :footer => delte_button} %>
                                            
            <% panel = '<div class="panel panel-default">
                    <div class="panel-heading">
                    '.html_safe+dialog_button+'
                    </div>
                    <div class="panel-body">
                    '.html_safe+image_tag(user.picture.url, alt: "Titelbild" )+'
                    </div>
                </div>'.html_safe %>                                            
            
            <%= panel %>
                    
                                     
                
            <% else %>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="picture_<%= user.id %>" >
                            <%= f.file_field :picture, class: "filestyle", id: "user_picture_"+user.id.to_s,accept: 'image/jpeg,image/gif,image/png' %>
                        </span>
                    </div>
                    <div id="upload_button_<%= user.id %>" style="display: none;" >
                        <div class="panel-body">
                            
                                <%= f.submit "Hochladen" do %><i class="fa fa-upload" aria-hidden="true"></i><% end %>
                            </div>
                    </div>
                </div>
            <% end %>
        </div>
        
        
    </div>
</div>     
        

<% end %>
<script type="text/javascript">
    function check_time_passed_for_change_for_user(input_change_time, user_id){
        if( last_change_made == input_change_time){
            update_for_user(user_id);
        }
    }
    
    function input_was_made_for_user(user_id){  
        last_change_made = new Date();
        change_saved(false);
        
        setTimeout(check_time_passed_for_change_for_user.bind(null, last_change_made, user_id), time_to_wait_until_save_changes_in_ms);
    }
    function update_for_user(user_id) {
      last_update_made = last_change_made;
      var user_name = $('#'+user_id).val();
     
      var request = void 0;
      request = $.ajax({type: "PUT",
                        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))}, //<!-- Damit bei einem AJAX Call der Auth. Token mitgesendet wird -->
                        dataType: "script",
                        url: '/users/'+user_id,
                        contentType: 'application/json',
                        data: JSON.stringify({ 'user': {'name': user_name
                                                        }, 'ajax' : true, _method:'put' })
                }).done(function( msg ){
                     input_successfull_saved();
                });
    };
    
    $('#user_picture_<%= user.id %>').attr("data-input",false);
    $('#user_picture_<%= user.id %>').attr("data-buttonText","Auswählen");
    $('#user_picture_<%= user.id %>').attr("data-buttonName","filebtn");
    
    $('#<%= user.id %>').on('input', function(){
       input_was_made_for_user(this.name);
    });
     
     $('#user_picture_<%= user.id %>').bind('change', function() {
        var fileName = $(this).val();
        var user_id = <%= user.id %>;
        show_submit_field_if_file_selectet_for_user(fileName,user_id);
    
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
      });
  
      function show_submit_field_if_file_selectet_for_user(fileName,user_id){
        $('#upload_button_'+user_id).toggle(fileName!="");
      }
</script>

app/views/users/_user.html.erb
<!-- Das ist die Miniaturansicht eines Users -->

<% firstname = user.firstname %>
<% lastname = user.lastname %>

<% title = firstname+" "+lastname %>

<% has_picture = user.picture? %>
<% if has_picture %>
    <% image = image_tag(user.picture.url) %>
<% else %>
    <% image = "Default Bild" %>
<% end %>

<!-- xs md lg -->
<div class="col-md-4">
    Debug: UserID: <%= user.id %>
    <div class="tab">
        <%= image %>    
    </div>
    <div class="tabcontent">
        <%= render "helper/panel" , locals: {:title => title, :body => "Mehr infos" } %>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h4>All users</h4>
    
<%= will_paginate %>    <!-- Zeigt nur reduzierte Anzahl an -->

<div class="row">
    <%= render @users %>    <!-- Rendert alle _user.html.erb -->
</div>
    
<%= will_paginate %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- Das ist die Vollständige Anzeige eines Users  -->

<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-12">
        <%= render "helper/panel" , locals: {:title => "User: "+@user.id.to_s, :body => "" } %>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Firstname: ", :body => @user.firstname } %>
    </div>
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Lastname: ", :body => @user.lastname } %>
    </div>
    
    <% if @user.picture? %>
        <div class="col-md-4">
            <%= render "helper/panel" , locals: {:title => "Bild: ", :body =>image_tag(@user.picture.url, alt: "Titelbild" ) } %>
        </div>  
    <% end %>

    <div class="col-md-4">
        <% gender_icon_name = @user.female ? "fa-venus" : "fa-mars" %>
        <% gender_icon = render "helper/icon" , locals: {:icon => gender_icon_name } %>
        <% gender_text = @user.female ? "Weiblich" : "Männlich" %>
        <% gender_body = gender_text+" "+gender_icon %>
        
        <%= render "helper/panel" , locals: {:title => "Geschlecht: ", :body => gender_body.html_safe } %>
    </div>

    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "PhoneNumber: ", :body => @user.phone_number } %>
    </div>
    
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Informationen: ", :body => @user.information } %>
    </div>
            
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Email: ", :body => @user.email } %>
    </div>
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Device", :body => @user.view_device_type } %>
    </div>
    <div class="col-md-4">
        <% department_body = render @user.department %>
        <%= render "helper/panel" , locals: {:title => "Department", :body => department_body } %>
    </div>
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Height", :body => @user.size.to_s } %>
    </div>
    
    <div class="col-md-12">
        <% professions = render @professions %>
        
        <% body = '<div class="row">'.html_safe+professions+'</div>'.html_safe %>
        <% paginate = will_paginate @professions, :param_name => 'professions_page' %>
        
        <%= render "helper/panel" , locals: {:title => "Professions", :body => body+paginate } %>
        
        
    </div>
    
</div>

app/views/users/watch.html.erb
<h1>Exemple module ActionController::Live and HTML5 Server Sent Events</h1>

<p>Crie um novo usuário com mais de um browser aberto nesta página e veja todos eles se atualizando</p>
<%= link_to 'Neuen Nutzer erstellen', new_user_path %>

<ul id="users">
</ul>

  <script type="text/javascript">
    var source = new EventSource('/user_stream');
    console.log("Started listening");
    source.addEventListener('results', function(e){
      console.log('Received a message:', e.data);
      $("#users").append("<li>"+ $.parseJSON(e.data).name +"</li>");
    });
    source.addEventListener('finished', function(e){
      console.log('Close:', e.data);
      source.close();
    });
</script>