config/routes.rb
# Diese Datei kümmert sich um das Weiterleiten der Browser Anfragen
Rails.application.routes.draw do
  
  # Zunächst definieren wir mit 'root', was unsere Startseite ist
  root 'static_pages#home'
  
  # SSE Test
  get 'user_stream' => 'users#index_stream'
  get 'user_watch' => 'users#watch'
  # SSE Ende Test

  # Definieren wir erstmal unsere nicht so interessanten Seiten
  # Es gibt einen Controller 'StaticPages', welcher uns einfach nur "statische"
  # Seiten Anzeigen lassen soll. 
  
  # Es gilt: get 'DieUrlDerSeite' => 'ControlerNamen # Methode'
  # Bsp. mit '...de/help' wird die Methode 'help' des Controller 'StaticPages'
  # aufgerufen
  get    'help'      => 'static_pages#help' 
  get    'home'      => 'static_pages#home' # Die Startseite
  get    'about'     => 'static_pages#about' 
  get    'contact'   => 'static_pages#contact'
  get    'admin_menu'=> 'static_pages#admin_menu' # Die Admin Menu Seite

  # Definieren wir als nächstes, welche Modelle wir sehen wollen
  # Die Standartmethoden werden hierdurch erlaubt
  resources :firecars
  resources :users
  resources :professions
  resources :departments
  resources :addresses
  resources :operations do
    member do
      # Weiterhin wird die Methode 'map' erlaubt/definiert
      # Diese leitet die Anfrage an den 'OperationController'
      # weiter an die gleichnamige Methode
      get 'map' 
    end
  end
  
  # Routen für Passwörter etc.
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
  get    'users/delete_picture' => 'users#delete_picture'
  get    'signup'    => 'users#new'
  
  

  
  
  post   'static_pages/call_controller_post_method' => 'static_pages#call_controller_post_method'
  get   'static_pages/call_controller_method' => 'static_pages#call_controller_method'
  
  # Routen zum erstellen einer Session
  get 'sessions/new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  
end

app/models/firecar.rb
class Firecar < ActiveRecord::Base
end

app/controllers/firecars_controller.rb
class FirecarsController < ApplicationController
  before_action :set_firecar, only: [:show, :edit, :update, :destroy]

  # GET /firecars
  # GET /firecars.json
  def index
    @firecars = Firecar.all
  end

  # GET /firecars/1
  # GET /firecars/1.json
  def show
  end

  # GET /firecars/new
  def new
    @firecar = Firecar.new
  end

  # GET /firecars/1/edit
  def edit
  end

  # POST /firecars
  # POST /firecars.json
  def create
    @firecar = Firecar.new(firecar_params)

    respond_to do |format|
      if @firecar.save
        format.html { redirect_to @firecar, notice: 'Firecar was successfully created.' }
        format.json { render :show, status: :created, location: @firecar }
      else
        format.html { render :new }
        format.json { render json: @firecar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firecars/1
  # PATCH/PUT /firecars/1.json
  def update
    respond_to do |format|
      if @firecar.update(firecar_params)
        format.html { redirect_to @firecar, notice: 'Firecar was successfully updated.' }
        format.json { render :show, status: :ok, location: @firecar }
      else
        format.html { render :edit }
        format.json { render json: @firecar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firecars/1
  # DELETE /firecars/1.json
  def destroy
    @firecar.destroy
    respond_to do |format|
      format.html { redirect_to firecars_url, notice: 'Firecar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firecar
      @firecar = Firecar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firecar_params
      params.fetch(:firecar, {})
    end
end

app/helpers/firecars_helper.rb
module FirecarsHelper
end

app/views/firecars/_form.html.erb
<%= form_for(@firecar) do |f| %>
  <% if @firecar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firecar.errors.count, "error") %> prohibited this firecar from being saved:</h2>

      <ul>
      <% @firecar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firecars/edit.html.erb
<h1>Editing Firecar</h1>

<%= render 'form' %>

<%= link_to 'Show', @firecar %> |
<%= link_to 'Back', firecars_path %>

app/views/firecars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Firecars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firecars.each do |firecar| %>
      <tr>
        <td><%= link_to 'Show', firecar %></td>
        <td><%= link_to 'Edit', edit_firecar_path(firecar) %></td>
        <td><%= link_to 'Destroy', firecar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firecar', new_firecar_path %>

app/views/firecars/new.html.erb
<h1>New Firecar</h1>

<%= render 'form' %>

<%= link_to 'Back', firecars_path %>

app/views/firecars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_firecar_path(@firecar) %> |
<%= link_to 'Back', firecars_path %>