config/routes.rb
# Diese Datei kümmert sich um das Weiterleiten der Browser Anfragen
Rails.application.routes.draw do
  
  # Zunächst definieren wir mit 'root', was unsere Startseite ist
  root 'static_pages#home'
  
  # SSE Test
  get 'user_stream' => 'users#index_stream'
  get 'user_watch' => 'users#watch'
  # SSE Ende Test

  # Definieren wir erstmal unsere nicht so interessanten Seiten
  # Es gibt einen Controller 'StaticPages', welcher uns einfach nur "statische"
  # Seiten Anzeigen lassen soll. 
  
  # Es gilt: get 'DieUrlDerSeite' => 'ControlerNamen # Methode'
  # Bsp. mit '...de/help' wird die Methode 'help' des Controller 'StaticPages'
  # aufgerufen
  get    'help'      => 'static_pages#help' 
  get    'home'      => 'static_pages#home' # Die Startseite
  get    'about'     => 'static_pages#about' 
  get    'contact'   => 'static_pages#contact'
  get    'admin_menu'=> 'static_pages#admin_menu' # Die Admin Menu Seite

  # Definieren wir als nächstes, welche Modelle wir sehen wollen
  # Die Standartmethoden werden hierdurch erlaubt
  resources :firecars
  resources :users
  resources :professions
  resources :departments
  resources :addresses
  resources :operations do
    member do
      # Weiterhin wird die Methode 'map' erlaubt/definiert
      # Diese leitet die Anfrage an den 'OperationController'
      # weiter an die gleichnamige Methode
      get 'map' 
    end
  end
  
  # Routen für Passwörter etc.
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  
  get    'users/delete_picture' => 'users#delete_picture'
  get    'signup'    => 'users#new'
  
  

  
  
  post   'static_pages/call_controller_post_method' => 'static_pages#call_controller_post_method'
  get   'static_pages/call_controller_method' => 'static_pages#call_controller_method'
  
  # Routen zum erstellen einer Session
  get 'sessions/new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  
  
end

app/models/operation.rb
class Operation < ActiveRecord::Base
    belongs_to :address
    belongs_to :chief, class_name: 'User'
    belongs_to :department
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.paginate(page: params[:page], :per_page => 10)
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @operation = Operation.find(params[:id])
    
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end
  
  # Die Funktion map ruft die gleichnamige Seite 'map.html.erb' auf und
  # übergibt Variablen.
  # Damit diese Funktion vom Routing gefunden wird, muss diese Aktion in
  # der Datei 'config/routes.rb' aktiviert werden
  def map
    @operation = Operation.find(params[:id])
    
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.fetch(:operation, {})
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<!-- Das ist die Miniaturansicht eines Users -->

<% title_name = operation.operation_type+" at "+operation.address.street %>
<% body = "Chief: "+operation.chief.email+"<br>"+"Activ: "+operation.activ.to_s %>

<% title = render "helper/button_link" , locals: {:link => operation,
                                            :center => title_name } %>

<!-- xs md lg -->
<div class="col-md-4">
    Debug: OperationID: <%= operation.id %>
    <div class="tabcontent">
        <%= render "helper/panel" , locals: {:title => title, :body => body.html_safe } %>
    </div>
</div>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<% provide(:title, 'All Operations') %>
<h4>All Operations</h4>
    
<%= will_paginate %>    <!-- Zeigt nur reduzierte Anzahl an -->

<div class="row">
    <%= render @operations %>    <!-- Rendert alle _user.html.erb -->
</div>
    
<%= will_paginate %>

app/views/operations/map.html.erb
<!-- Diese Datei wurde aufgerufen durch die definierte Methode 'map' in
    'OperationController', dort definierte Variablen, können nun verwendet
    werden -->

<h1>Map</h1>

Diese Seite sollte zunächst erweitert werden, sodass ein SSE (Server Sent Event) eingebunden wurde.
Dadurch sollen neue Daten an diese Seite gesendet werden, sofern es was neues gibt.

<%= render "helper/button_back" , locals: {:link => @operation } %>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<!-- Das ist die Vollständige Anzeige eines Users  -->

<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-12">
        <%= render "helper/panel" , locals: {:title => "Operation: "+@operation.id.to_s, :body => "" } %>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Operation Type: ", :body => @operation.operation_type } %>
    </div>
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Address: ", :body => @operation.address.street } %>
    </div>
    
    <div class="col-md-4">
        <% link_to_chief = render "helper/button_link" , locals: {:link => @operation.chief,
                                            :center => @operation.chief.firstname+" "+@operation.chief.lastname } %>
        <%= render "helper/panel" , locals: {:title => "Chief: ", :body => link_to_chief } %>
    </div>
    
    <div class="col-md-4">
        <% link_to_department = render "helper/button_link" , locals: {:link => @operation.department,
                                            :center => @operation.department.name } %>
        <%= render "helper/panel" , locals: {:title => "Department: ", :body => link_to_department } %>
    </div>
    
    <div class="col-md-4">
        <% link_to_map = render "helper/button_link" , locals: {:link => @operation, :action => "map",
                                            :center => "Karte" } %>
        <%= render "helper/panel" , locals: {:title => "Map: ", :body => link_to_map } %>
    </div>
            
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Activ: ", :body => @operation.activ.to_s } %>
    </div>
    <div class="col-md-4">
        <%= render "helper/panel" , locals: {:title => "Date", :body => @operation.time_started.to_s } %>
    </div>
    
</div>